networks:
  vector_db_testing:
    name: vector_db_testing
    external: true

services:
  vectorizer:
    build: .
   # runtime: nvidia
    volumes:
      - ./images:/vectorizer/images
      - ./main.py:/vectorizer/main.py
      - ./logs:/vectorizer/logs
      - ./output:/vectorizer/output
      - ./app:/vectorizer/app
      # Add mapping for the image folder (if external, e.g., HDD)
    networks:
      - vector_db_testing
    environment:
      MODEL: "${MODEL:-dino}"
      DIR: "${DIR:-./images/NORTHSTORM/2024}"
    command:
      - python3
      - main.py
      - --model
      - "${MODEL}"
      - --dir
      - "${DIR}"