
networks:
  vector_db_testing:
    name: vector_db_testing
    external: true

services:
  milvus:
    image: milvusdb/milvus:v2.4.17
    environment:
      ETCD_USE_EMBED: true
      ETCD_DATA_DIR: /var/lib/milvus/etcd
      ETCD_CONFIG_PATH: /milvus/configs/embedEtcd.yaml
      COMMON_STORAGETYPE: local
    networks:
      - vector_db_testing
    volumes:
      - ./volumes/milvus:/var/lib/milvus # todo - remove this (probably)
      - ./embedEtcd.yaml:/milvus/configs/embedEtcd.yaml
      - ./user.yaml:/milvus/configs/user.yaml
    ports:
      - 19530:19530
      - 9091:9091
      - 2379:2379
    healthcheck:
      test: ["curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      timeout: 20s
      retries: 5
      start_period: 30s
    command: ["milvus", "run", "standalone"]