version: '3.9'

networks:
  vector_db_testing:
    name: vector_db_testing
    external: true

services:
  pgvector:
    image: pgvector/pgvector:0.8.0-pg17
    container_name: pgvector_db
    environment:
      POSTGRES_USER: vbenchmarkusr
      POSTGRES_PASSWORD: vbenchmarkpass
      POSTGRES_DB: vbenchmarkdb
    networks:
      - vector_db_testing
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./config:/config
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vbenchmarkusr -d vbenchmarkdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  db-data:
