version: '3.9'

networks:
  vector_db_testing:
    name: vector_db_testing
    external: true

services:
  qdrant:
    image: qdrant/qdrant:v1.13.2
    container_name: qdrant_db
    networks:
      - vector_db_testing
    volumes:
      - db-data:/qdrant/storage
      - ./config:/config
    ports:
      - "6333:6333"
    restart: always

volumes:
  db-data:
